# Form implementation generated from reading ui file 'currency.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
import currencyapicom 
from datetime import date

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        self.response = self.getData()
        self.data = self.response.currencies()
        self.cur = self.getAllCurrencies(self.data["data"])
        self.cur.sort()

        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(170, 120, 191, 16))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 150, 220, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.convertFromLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.convertFromLabel.setObjectName("convertFromLabel")
        self.horizontalLayout.addWidget(self.convertFromLabel)
        self.convertFromBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.convertFromBox.setObjectName("convertFromBox")
        self.convertFromBox.addItems(self.cur)
        self.horizontalLayout.addWidget(self.convertFromBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 201, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ConvertFromAmount = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.ConvertFromAmount.setObjectName("ConvertFromAmount")
        self.ConvertFromAmount.validator = QtGui.QDoubleValidator()
        self.ConvertFromAmount.textChanged.connect(self.convert)

        self.horizontalLayout_2.addWidget(self.ConvertFromAmount)
        self.convertbtn = QtWidgets.QPushButton(parent=Form)
        self.convertbtn.setGeometry(QtCore.QRect(180, 220, 113, 32))
        self.convertbtn.setObjectName("convertbtn")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(270, 150, 197, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ConvertToLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.ConvertToLabel.setObjectName("ConvertToLabel")
        self.horizontalLayout_3.addWidget(self.ConvertToLabel)
        self.convertToBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_3)
        self.convertToBox.setObjectName("convertToBox")
        self.convertToBox.addItems(self.cur)
        self.horizontalLayout_3.addWidget(self.convertToBox)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(270, 180, 201, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ConvertedAmount = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_4)
        self.ConvertedAmount.setObjectName("ConvertedAmount")
        # self.ConvertedAmount.textChanged.connect(self.reverseConvert)
        self.horizontalLayout_4.addWidget(self.ConvertedAmount)
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Currency Convertor"))
        self.convertFromLabel.setText(_translate("Form", "Convert From:"))
        self.ConvertFromAmount.setPlaceholderText(_translate("Form", "Enter amount to convert here"))
        self.convertbtn.setText(_translate("Form", "Convert"))
        self.ConvertToLabel.setText(_translate("Form", "Convert To:"))
        self.ConvertedAmount.setPlaceholderText(_translate("Form", "Converted Amount"))
    
    def getData(self):
        return currencyapicom.Client("cur_live_CZ8QPY8bVVNSQm4Q8KQ1c7h1kZhJNyjqikspmMBz")
    
    
    
    def getAllCurrencies(self, data):
        cur = self.getCurrency(data)
        return cur

    def getCurrency(self, datas):
        arr = []
        for data in datas:
                arr.append(datas[data]["name"])
        return arr
    def getSymbol(self, datas, name):
        for data in datas:
            if(datas[data]["name"] == name):
                return datas[data]["code"]
    def convert(self):
        fromCur = self.getSymbol(self.data["data"], self.convertFromBox.currentText())
        toCur = self.getSymbol(self.data["data"], self.convertToBox.currentText())
       
        amount = float(self.ConvertFromAmount.text())
        try:
            data = self.response.latest(fromCur)
            converted = amount * data["data"][toCur]["value"]
            converted = round(converted, 2)
            self.ConvertedAmount.setText(str(converted))
        except Exception as e:
            print("error")
            print(e)
            self.ConvertedAmount.setText("Error")
            self.ConvertedAmount.setStyleSheet("color: red")
    
    # def reverseConvert(self):
    #     fromCur = self.getSymbol(self.data["data"], self.convertFromBox.currentText())
    #     toCur = self.getSymbol(self.data["data"], self.convertToBox.currentText())
       
    #     amount = float(self.ConvertFromAmount.text())
    #     try:
    #         data = self.response.latest(toCur)
    #         converted = amount * data["data"][fromCur]["value"]
    #         converted = round(converted, 2)
    #         self.ConvertFromAmount.setText(str(converted))
    #     except Exception as e:
    #         print("error")
    #         print(e)
    #         self.ConvertedAmount.setText("Error")
    #         self.ConvertedAmount.setStyleSheet("color: red")

        
    
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
