"""
This is a setup.py script generated by py2applet

This file was used for to create the mac executable file.
"""

from setuptools import setup

APP = ['Main.py']
DATA_FILES = ['convert.py', 'currencyConvertor.py', 'UrlShortener.py', 'ytDownload.py']
OPTIONS = {'iconfile': 'logo.ico'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)


