# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyshorteners


class Ui_Title(object):
    def setupUi(self, Title):
        Title.setObjectName("Title")
        Title.resize(500, 500)
        self.label = QtWidgets.QLabel(parent=Title)
        self.label.setGeometry(QtCore.QRect(200, 80, 211, 16))
        self.label.setObjectName("label")
        self.shortbtn = QtWidgets.QPushButton(parent=Title)
        self.shortbtn.setGeometry(QtCore.QRect(200, 170, 120, 32))
        self.shortbtn.setObjectName("shortbtn")
        self.shortbtn.clicked.connect(self.shorten)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Title)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 481, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.initialUrl = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.initialUrl.setObjectName("initialUrl")
        self.horizontalLayout.addWidget(self.initialUrl)
        self.initialUrlEdit = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.initialUrlEdit.setObjectName("initialUrlEdit")
        self.horizontalLayout.addWidget(self.initialUrlEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Title)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 481, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.shortenLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.shortenLabel.setObjectName("shortenLabel")
        self.horizontalLayout_2.addWidget(self.shortenLabel)
        self.ShortenLine = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.ShortenLine.setObjectName("ShortenLine")
        
        self.shortenLabel.hide()
        self.ShortenLine.hide()
        self.horizontalLayout_2.addWidget(self.ShortenLine)
        

        self.retranslateUi(Title)
        QtCore.QMetaObject.connectSlotsByName(Title)

    def retranslateUi(self, Title):
        _translate = QtCore.QCoreApplication.translate
        Title.setWindowTitle(_translate("Title", "Form"))
        self.label.setText(_translate("Title", "URL Shortener"))
        self.shortbtn.setText(_translate("Title", "Shorten"))
        self.initialUrl.setText(_translate("Title", "URL to Shorten:"))
        self.shortenLabel.setText(_translate("Title", "Shortened URL:"))
    def shorten(self):
        url = self.initialUrlEdit.text()
        s = pyshorteners.Shortener()
        self.ShortenLine.setText(s.tinyurl.short(url))
        self.ShortenLine.show()
        self.shortenLabel.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Title = QtWidgets.QWidget()
    ui = Ui_Title()
    ui.setupUi(Title)
    Title.show()
    sys.exit(app.exec())
